AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  GenerateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.app.lambda_handler
      Runtime: python3.13
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName  # Dynamisk bucket-navn fra parameteren
      Events:
        GenerateImageAPI:
          Type: Api
          Properties:
            Path: /generate-image
            Method: post

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName  # Bruker samme parameter for S3-bucketnavn

Parameters:
  S3BucketName:
    Type: String
    Default: pgr301-couch-explorers-kandidat42  # Sett et standardverdi for S3-bucketnavnet
    Description: "S3 bucket name for storing generated images"
